package org.noorm.jdbc.platform;

import org.noorm.jdbc.FilterExtension;
import org.noorm.jdbc.QueryColumn;

import javax.sql.DataSource;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Map;

/**
 * @author Ulf Pietruschka / ulf.pietruschka@etenso.com
 *         Date: 11.02.14
 *         Time: 13:48
 */
public interface IPlatform {

    /**
     * Returns the name of platform service provider
     *
     * @return the platform name
     */
    String getName();

    /**
     * Creates a platform specific data source.
     *
     * @param pURL the connection URL
     * @param pUsername the username
     * @param pPassword the password
     * @return the established data source
     * @throws SQLException JDBC driver exception
     */
    DataSource getDataSource(final String pURL, final String pUsername, final String pPassword) throws SQLException;

    /**
     * Validates the platform specific data source
     *
     * @param pDataSource the data source
     * @return a textual summary of the data source validation
     * @throws SQLException JDBC driver exception
     */
    String validateDataSource(final DataSource pDataSource) throws SQLException;

    /**
     * Returns the platform specific query to retrieve a sequence value generated by the database.
     *
     * @param pSequenceName the name of the database sequence
     * @return the SELECT statement to retrieve a single sequence value for the given platform
     */
    String getSequenceQuery(final String pSequenceName);

    /**
     * Executes a batch over a prepared statement.
     * Different databases and JDBC drivers handle the update count differently. To get a reliable update,
     * a platform specific implementation is required.
     *
     * @param pPreparedStatement the prepared statement ready for executing the next batch
     * @return the reliable update count for the platform in use
     * @throws SQLException JDBC driver exception
     */
    int executeBatchWithReliableCount(final PreparedStatement pPreparedStatement) throws SQLException;

    /**
     * Sets an object value for an DML statement (INSERT, UPDATE, DELETE).
     *
     * @param pStmt the prepared SQL statement
     * @param pValue the parameter value to be set
     * @param pParameterIndex the index of the parameter
     * @param pSQLType the SQL type. Usually one type specified in java.sql.Types or a proprietary type
     * @throws SQLException JDBC driver exception
     */
    void setObject(final PreparedStatement pStmt,
                   final Object pValue,
                   final int pParameterIndex,
                   final int pSQLType) throws SQLException;

    /**
     * Binds a numeric array to a callable statement.
     *
     * @param pCon the JDBC connection
     * @param pCstmt the JDBC callable statement
     * @param pValue the value to bind (numeric array)
     * @param pParameterIndex the parameter index
     * @throws SQLException JDBC driver exception
     */
    void prepareNumericArray(final Connection pCon,
                             final CallableStatement pCstmt,
                             final Object pValue,
                             final int pParameterIndex) throws SQLException;

    /**
     * The REF_CURSOR JDBC type is used to directly utilize a SQL cursor established from within
     * a stored procedure for a JDBC ResultSet. However, though we have JDBCType.REF_CURSOR, this
     * does not necessarily match the vendor type, so we can provide the vendor type here.
     *
     * @return the REF_CURSOR JDBC type
     */
    int getRefCursorJDBCType();

    /**
     * Constructs a SQL query based on the provided information.
     *
     * @param pTableName the table name
     * @param pInParameters the query parameters
     * @param pUseNamedParameters whether to use named parameters or not
     * @param pAcquireLock lock the retrieved data for further processing
     * @param pFilterExtension paging and sorting information
     * @return the constructed SQL query
     */
    String buildSQLStatement(final String pTableName,
                             final Map<QueryColumn, Object> pInParameters,
                             final boolean pUseNamedParameters,
                             final boolean pAcquireLock,
                             final FilterExtension pFilterExtension);

    /**
     * Provides database metadata for code generation and validation of generated code.
     *
     * @return the platform specific implementation of the metadata retrieval functionality
     */
    IMetadata getMetadata();
}
