package org.noorm.platform;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * @author Ulf Pietruschka / ulf.pietruschka@ext.secunet.com
 *         Date: 11.02.14
 *         Time: 13:52
 *         <p/>
 *         Project class implementation
 */
public class MSSQLPlatform implements IPlatform {

    /**
     * Returns the platform specific query to retrieve a sequence value generated by the database.
     *
     * @param pSequenceName the name of the database sequence
     * @return the SELECT statement to retrieve a single sequence value for the given platform
     */
    @Override
    public String getSequenceQuery(final String pSequenceName) {

        final String sequenceQuery = "SELECT NEXT VALUE FOR  ".concat(pSequenceName);
        return sequenceQuery;
    }

    /**
     * Executes a batch over a prepared statement.
     * Different databases and JDBC drivers handle the update count differently. To get a reliable update,
     * a platform specific implementation is required.
     *
     * @param pPreparedStatement the prepared statement ready for executing the next batch
     * @return the reliable update count for the platform in use
     */
    @Override
    public int executeBatchWithReliableCount(final PreparedStatement pPreparedStatement) throws SQLException {

        final int[] batchCounts = pPreparedStatement.executeBatch();
        int updateCount = 0;
        for (int i = 0; i < batchCounts.length; i++) {
            updateCount += batchCounts[i];
        }
        return updateCount;
    }

    /**
     * Sets an object value for an DML statement (INSERT, UPDATE, DELETE).
     *
     * @param pStmt           the prepared SQL statement
     * @param pValue          the parameter value to be set
     * @param pParameterIndex the index of the parameter
     * @param pSQLType        the SQL type. Usually one type specified in java.sql.Types or a proprietary type
     * @throws java.sql.SQLException
     */
    @Override
    public void setObject(final PreparedStatement pStmt,
                          final Object pValue,
                          final int pParameterIndex,
                          final int pSQLType) throws SQLException {

        if (pValue == null) {
            pStmt.setNull(pParameterIndex, pSQLType);
        } else {
            pStmt.setObject(pParameterIndex, pValue, pSQLType);
        }
    }
}
